export const GENERATE_OTP_REQUEST='GENERATE_OTP_REQUEST';
export const GENERATE_OTP_SUCCESS='GENERATE_OTP_SUCCESS';
export const GENERATE_OTP_ERROR='GENERATE_OTP_ERROR';

export const VERIFY_OTP_REQUEST='VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS='VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_ERROR='VERIFY_OTP_ERROR';
