export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';
export const UPDATE_REFRESH_TOKEN = 'UPDATE_REFRESH_TOKEN';

export const UPDATE_AUTH_STATE = 'UPDATE_AUTH_STATE';